# Generated by Django 6.0.4 on 2026-04-10 03:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('occupancy', models.BooleanField(default=False)),
                ('last_motion', models.DateTimeField(blank=True, null=True)),
                ('energy_saved_today', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='MotionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(max_length=50)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('on', 'Active'), ('off', 'Ended')], max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.room')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EnergyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_on', models.FloatField()),
                ('energy_saved', models.FloatField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_logs', to='api.room')),
            ],
            options={
                'unique_together': {('room', 'date')},
            },
        ),
    ]
