# Generated by Django 6.0.4 on 2026-04-26 01:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventlog_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energylog',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='profile',
            name='assigned_rooms',
            field=models.ManyToManyField(blank=True, related_name='assigned_profiles', to='api.room'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('professor', 'Professor'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='energylog',
            name='energy_saved',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='energylog',
            name='hours_on',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='api.room'),
        ),
        migrations.AlterField(
            model_name='motionevent',
            name='duration',
            field=models.CharField(blank=True, default='—', max_length=50),
        ),
        migrations.AlterField(
            model_name='motionevent',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='motionevent',
            name='status',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='on', max_length=10),
        ),
        migrations.AlterField(
            model_name='motionevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trigger', models.CharField(choices=[('no_motion', 'No motion detected'), ('motion', 'Motion detected'), ('lights_on', 'Lights turn ON'), ('lights_off', 'Lights turn OFF'), ('time_of_day', 'Time of day')], max_length=50)),
                ('action', models.CharField(choices=[('lights_off', 'Turn lights OFF'), ('lights_on', 'Turn lights ON'), ('notify', 'Send notification'), ('log_event', 'Log event')], max_length=50)),
                ('delay_minutes', models.IntegerField(default=5)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='api.room')),
            ],
        ),
    ]
